baseurl = "/"
title = "Thoughts & experiments by Vaibhav"
author = "Vaibhav Pandey"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Vaibhav's desk"
  author = "Vaibhav Pandey"
  dateFormat = "2019/01/02"

[[menu.main]]
    name = "Medium"
    url = "https://medium.com/vaibhav31"
    weight = 1
[[menu.main]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/vaibhavpandey45/"
    weight = 2
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/vaibhav_pandey"
    weight = 3
[[menu.main]]
    name = "Github"
    url = "https://github.com/fcvaibhav"
    weight = 4
[[menu.main]]
    name = "Dvis"
    url = "/data.rmd"
    weight = 5
